spring:
  application:
    name: workout-progress-tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/workout_progress_tracker
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  
google:
  sheets:
    spreadsheet-id: TWOJ_SPREADSHEET_ID
    credentials-path: classpath:credentials/service-account.json
    application-name: workout-progress-tracker